### ISSUE TITLE
Command line tool: Connection interrupted

### ISSUE THREAD

**Issue by jjcaballero** [vashpan/xcode-dev-cleaner#23]
When I run the command line with a regular user, I get "Connection interrupted".

```
$ /Applications/DevCleaner.app/Contents/Resources/dev-cleaner.sh info
DevCleaner 2.2.0 (380)

2021-04-07 06:17:31.519 DevCleaner[79657:13329779] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
```

Note that with the admin user, I don't see this error but I face another issue https://github.com/vashpan/xcode-dev-cleaner/issues/22.

Do the users need special permissions? Is there a way to overcome this problem?

Thanks!

**Comment by jjcaballero** [comment]
Thanks @vashpan 
Can you please elaborate a bit to understand better the issue? 
What do you mean by "non-interactive" environment? those that run the dev-cleaner tool from the command line?
Then, what are the implications? Does this affect the usage of the tool with admin users too?

**Comment by jjcaballero** [comment]
@vashpan sorry, I didn't mean to close it

**Comment by vashpan** [comment]
> What do you mean by "non-interactive" environment? those that run the dev-cleaner tool from the command line?
> Then, what are the implications? Does this affect the usage of the tool with admin users too?

Yes, I meant command line. 

DevCleaner, as all Mac App Store apps, must run within sandbox, which basically means that by default, app doesn't see anything else on the computer besides it's own app bundle and it's container for its files (more or less like on iOS). To get r/w access to different part of the filesystem (in our case, `~/Library/Developer` folder), user must point manually to this location, usually via "open location" system dialogue.

There's also a [mechanism](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16), called "app-scoped bookmarks" that allows to "save" an "access" to location that was previously set by the user. Sadly it seems that this access works only for some period of time and app needs to ask again after a while.

When running DevCleaner from command line, it still runs in sandbox, so it needs access to `~/Library/Developer` folder, so the dialogue is presented from time to time. For this reason, it limits usefulness of command line tool only to situations where you have access to the computer. It most likely won't work reliably if you run as part of your CI, or periodically via launchd/cron scheduling for example.

Having DevCleaner on sandbox is still something I'm thinking about - it's not needed of course and will allow for much better clean possibilities - but I would loose Mac App Store as distribution/update method which is important for me.

**Comment by vashpan** [comment]
After recent changes in handling "sandbox file bookmarks" in 2.3.x I think this issue should be fixed now 🤔

**Comment by jjcaballero** [comment]
I am using version 2.3.1 and I am afraid I still see the same error:

```
$ /Applications/DevCleaner.app/Contents/MacOS/DevCleaner info
DevCleaner 2.3.1 (425)

2022-03-21 04:11:06.997 DevCleaner[96631:5406818] XType: com.apple.fonts is not accessible.
2022-03-21 04:11:06.997 DevCleaner[96631:5406818] XType: XTFontStaticRegistry is enabled.
2022-03-21 04:11:07.006 DevCleaner[96631:5406839] In void modifyShouldRestoreOnRelaunchCounter(int32_t), _LSSetApplicationInformationItem(_kLSPersistenceSuppressRelaunchAtLoginKey) returned error -600
2022-03-21 04:11:07.040 DevCleaner[96631:5406818] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2022-03-21 04:11:17.065 DevCleaner[96631:5406818] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'HostCallsAuxiliary': Connection interrupted
```

**Comment by vashpan** [comment]
Ok, so this is probably related to this one: https://github.com/vashpan/xcode-dev-cleaner/issues/27

**Comment by jjcaballero** [comment]
That's strange. I am running it from the command line and the error message is different.

**Comment by vashpan** [comment]
@jjcaballero  Could you run it from GUI and check if file access popup shows up?

**Comment by jjcaballero** [comment]
Sure, I just ran it and the execution finished normally and it actually cleaned-up 5GB of disk space.
